### ISSUE TITLE
Request: Adding new chain if it does not exist.

### ISSUE THREAD

**Issue by Visual917** [thirdweb-dev/react#144]
It would be legendary if we added a new chain if it didn't exist on the Metamask of the user.

Is it possible somehow?

**Comment by jnsdls** [comment]
hey @Visual917 this should already be the behavior of the react SDK. Is this not working for you?

**Comment by Visual917** [comment]
> hey @Visual917 this should already be the behavior of the react SDK. Is this not working for you?

I am terribly sorry. It does work now. I should've known better. I used 3rdweb hybridly with thirdweb, the new version. Now everything works! Thank you..
