### ISSUE TITLE
Can't import thirdweb-dev/react into Replit

### ISSUE THREAD

**Issue by mpvolt** [thirdweb-dev/react#15]
Getting this error while trying to import {useAddress, useMetamask, useEditionDrop} from '@thirdweb-dev/react';

**Failed to compile.

./node_modules/wagmi-core/dist/wagmi-core.esm.js 256:5
Module parse failed: Unexpected token (256:5)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class InjectedConnector extends Connector {
>   id = 'injected';
|   ready = typeof window != 'undefined' && !!window.ethereum;
|   #provider;**

**Comment by jnsdls** [comment]
@mpvolt thanks for the report, we'll take a look at this shortly

**Comment by jnsdls** [comment]
hey @mpvolt I believe this should be fixed, take a look here: https://replit.com/@thirdweb-dev/react-sdk#src/App.jsx

Please feel free to re-open this issue if you still run into issues!
