### ISSUE TITLE
react-icons all icons are being imported? Huge first JS load size

### ISSUE THREAD

**Issue by Velozity** [thirdweb-dev/react#18]
Not entirely sure if I'm missing something, but my load times have been drastically slower since installing and first load JS time increased to 1.49mb.
![reacticonssize](https://user-images.githubusercontent.com/14904436/161416476-9b288272-4acd-4cbe-a662-4aa2086c298c.png)
![image](https://user-images.githubusercontent.com/14904436/161416543-574b6277-52ba-4ede-97db-35986e2d0641.png)

Some importing issues?

**Comment by jnsdls** [comment]
hey @Velozity, thanks for the report, we'll take a look at it

**Comment by jnsdls** [comment]
fixed in https://github.com/thirdweb-dev/react/releases/tag/v2.0.4
