### ISSUE TITLE
Repository not found for thirdweb sdk

### ISSUE THREAD

**Issue by crevulus** [thirdweb-dev/react#19]
I am trying to do the basic steps in your tutorials, e.g. here: https://portal.thirdweb.com/guides/mint-nft-using-nextjs#3-client-side-react-components-to-render-list-of-nfts-using-react-sdk-and-a-mint-button

However, every time I try to install the necessary packages I get an error saying the repo where your package is hosted cannot be found:

```sh
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/thirdweb-dev/sdk.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

I can install other packages just fine; it only affects this one.

Is this an issue with v2? I was also able to instal the old sdk packages (@3rdweb/hooks, for example) with no problems.

**Comment by jnsdls** [comment]
hey @crevulus, thanks for the report. it's odd that in the npm install it tries to do anything with github at all. I'm assuming your following the install steps from the guide you linked?

```sh
npm install @thirdweb-dev/react thirdweb-dev/sdk ethers
```

If so I can try to reproduce it. 

It might also be helpful if you could provide your npm version `npm -v` and node version `node -v`

**Comment by crevulus** [comment]
@jnsdls 
yarn: 1.22.10
npm: 8.1.0
node: v16.13.0

**Comment by jnsdls** [comment]
thanks! I'll try it out shortly and see if I can reproduce it on my end

**Comment by crevulus** [comment]
Actually, I think I've just spotted it. You're missing an `@` in the command for the sdk package name. Should be `@thirdweb-dev/sdk`. I tried editing it myself but couldn't find your docs, only your example code. @jnsdls

**Comment by jnsdls** [comment]
hey @crevulus, sorry about that just found the error (and fixing it in the guide itself) it's the missing `@` in the `thirdweb-dev/sdk`

**Comment by jnsdls** [comment]
> Actually, I think I've just spotted it. You're missing an `@` in the command for the sdk package name. Should be `@thirdweb-dev/sdk`. I tried editing it myself but couldn't find your docs, only your example code. @jnsdls

hah! yup exactly that should be `@thirdweb-dev/sdk` we'll fix it shortly!

**Comment by jnsdls** [comment]
will keep this open until we've fixed the guide(s)

**Comment by nachoiacovino** [comment]
Thank you for the report @crevulus! We just fixed the error in the guide:

https://github.com/thirdweb-dev/portal/commit/0ef8af2835331b0f5f986aa6c95f9b83fb1028ec
