### ISSUE TITLE
login in mobie with metamask

### ISSUE THREAD

**Issue by mfer-mickey** [thirdweb-dev/react#28]
now, I can login in by using useMetamask for web,but i can't login in mobile

**Comment by jnsdls** [comment]
> now, I can login in by using useMetamask for web,but i can't login in mobile

hey @mfer-mickey, to login with `useMetamask` on mobile you'd have to be within the in-app browser of metamask. it should work at that point. If your not using the metamask in-app browser you can use `useWalletConnect` and chose the metamask option within it for mobile login.

Let me know if that solves the issue or if there are problems even when following those steps!

**Comment by jnsdls** [comment]
stale
