### ISSUE TITLE
Error: Invariant failed: WalletLink / Coinbase connector not found, please make sure it is provided to your <ThirdwebProvider />

### ISSUE THREAD

**Issue by alaaan** [thirdweb-dev/react#30]
Out of nowhere I started getting this error being thrown in my Next.js project.  Even with just the JS starter project, immediately after adding in useCoinbaseWallet hook. Have a solid app that has been under testing last two weeks with no issue. ive had varying different configs for the ThirdWebProvider, but it fails even with the defaults?  Any suggestions?

**Comment by jnsdls** [comment]
thanks for the report @alaaan, this is fixed in `2.0.7`: https://github.com/thirdweb-dev/react/releases/tag/v2.0.7
