### ISSUE TITLE
useDisconnect(); is not working

### ISSUE THREAD

**Issue by worlkd** [thirdweb-dev/react#60]
useDisconnect(); function is not really working.
The Dapp website is always connected on MM

**Comment by jnsdls** [comment]
hey @worlkd, thanks for reaching out.

This is actually a long-standing issue with MetaMask itself. The MM extension does not provide any way for a dApp to properly disconnect.

The common "solution" (that this package implements by default as well) is to handle the disconnected state with a key in the browser's `localstorage`. This makes the app show as "logged out" but if you check the MM extension itself it will indeed still show as "connected".

The only way to actually fully disconnect MM from a dApp is to do it from the MM extension. This is just a limitation of MetaMask that (sadly) we have no control over.
