### ISSUE TITLE
coinbase cookies

### ISSUE THREAD

**Issue by 7flash** [thirdweb-dev/react#64]
when I try to authorize with metamask.. its writing some values to my local storage.. not sure what's the purpose..  even though I didn't include coinbase wallet option..

![image](https://user-images.githubusercontent.com/4569866/169792377-24c791ab-bf2e-448f-99ce-9fb8d46016e0.png)

**Comment by nachoiacovino** [comment]
Hello @7flash , do you have Coinbase Wallet also installed in your browser?

**Comment by 7flash** [comment]
> Hello @7flash , do you have Coinbase Wallet also installed in your browser?

nope

**Comment by nachoiacovino** [comment]
Okay thank you for the info, we default to enabling CB Wallet, WalletConnect and MetaMask to have them ready to go. cc @jnsdls for confirmation.

On our next react version, we will make it so you pass which wallets you want to support (with the addition to supporting more wallets, so this issue should be fixed then, we're. working on this.

Sorry for the trouble in the meantime.

**Comment by jnsdls** [comment]
Yep, these local storage values are being written by the coinbase-wallet SDK. Nacho covered it pretty closely.

We'll add more granular control of which exact wallets you would like to support in your dApp in the next upgrade of the react sdk which should ship within the next 1-2 weeks.

I'm closing this for now but will reference it back when that update ships. Thanks again for bringing this up @7flash! :)
