### ISSUE TITLE
Unable to use ThirdwebWeb3Provider in Next Js using Typescript

### ISSUE THREAD

**Issue by NoxinDVictus** [thirdweb-dev/react#67]
I'm Using Next Js with typescript. I keep getting the error message ```Type '{ children: (string | Element)[]; supportedChainIds: number[]; connectors: { injected: {}; }; }' is not assignable to type 'IntrinsicAttributes & ThirdwebWeb3ProviderProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & ThirdwebWeb3ProviderProps'.``` not sure what part is wrong, I did follow the instruction on how to set up @3rdweb/hooks

![Screen Shot 2022-05-24 at 2 30 26 PM](https://user-images.githubusercontent.com/58176922/169974204-ff809922-99a7-40a4-bdab-6228b93fdd76.png)
e

```
import { ThirdwebWeb3Provider } from '@3rdweb/hooks';
import type { AppProps } from 'next/app';
import 'regenerator-runtime/runtime';

// SOURCE: https://dev.to/byteslash/metamask-authentication-in-nextjs-with-third-web-55ff
// setting up auth with @3rdweb

function MyApp({ Component, pageProps }: AppProps) {
  const supportedChainIds = [1, 4];

  const connectors = {
    injected: {},
  };

  return (
    <ThirdwebWeb3Provider
      supportedChainIds={supportedChainIds}
      connectors={connectors}
    >
      <Component {...pageProps} />;
    </ThirdwebWeb3Provider>
  );
}

export default MyApp;

```

**Comment by jarrodwatts** [comment]
@NoxinDVictus `@3rdweb/hooks` is deprecated, please use `@thirdweb-dev/react` instead.
