### ISSUE TITLE
[Bug]: Must be used within Provider

### ISSUE THREAD

**Issue by ModaxDev** [thirdweb-dev/react#96]
Hey, 
i'm having this bugs when im trying to access to my address, my code : 
 "@thirdweb-dev/react": "^2.4.6",
    "@thirdweb-dev/sdk": "^2.3.20",
"ethers": "^5.6.9",

inside index.tsx got the provider

<ThirdwebProvider desiredChainId={ChainId.Mainnet}>
      <UserProvider>
        <QueryClientProvider client={queryClient}>
          <Base>
            <List />
          </Base>
        </QueryClientProvider>
      </UserProvider>
    </ThirdwebProvider>
    
Inside My compo
    
  import React from 'react';

import { useAddress, useDisconnect, useMetamask } from '@thirdweb-dev/react';

const AuthMetamask = () => {
  const connectWithMetamask = useMetamask();
  const address = useAddress();
  const disconnectWallet = useDisconnect();
  if (!address) {
    return (
      <button className="ml-auto" onClick={connectWithMetamask}>
        Connect Wallet
      </button>
    );
  }

  return (
    <div className="ml-auto flex flex-col">
      <button onClick={disconnectWallet}>Disconnect</button>
      <span>
        Connected to {address.substring(0, 5)}...{address.slice(-4)}
      </span>
    </div>
  );
};

export default AuthMetamask;

I'm using Next js 12.1 and react 17.0.2

Thanks

**Comment by nachoiacovino** [comment]
Did you wrap your app in a provider in your `_app.jsx`?

More info here: https://portal.thirdweb.com/react
